# Generated by Django 4.1.7 on 2023-10-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fashionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='author',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='datewritten',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
