# Generated by Django 4.1.7 on 2023-10-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fashionitem_author_fashionitem_datewritten'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='Carbs', max_length=100),
            preserve_default=False,
        ),
    ]
